import { Template } from "@/types"

export const templates: Template[] = [
  {
    id: "1",
    title: "SaaS Command Center",
    slug: "saas-command-center",
    description: "A production-grade SaaS dashboard with real-time analytics, user management, subscription billing integration, and role-based access control. Built for scale with server-side rendering and edge caching.",
    category: "saas",
    techStack: ["Next.js 14", "Tailwind CSS", "Clerk Auth", "Neon DB", "Stripe"],
    features: [
      "Real-time analytics with Recharts",
      "Role-based access control",
      "Subscription billing ready",
      "Dark mode by default",
      "Responsive data tables",
      "Webhook handling for events",
    ],
    priceUsd: 49,
    priceKes: 6500,
    isFree: false,
    livePreviewUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
    screenshots: [],
    isPublished: true,
    downloadCount: 1247,
  },
  {
    id: "2",
    title: "Apex Commerce Engine",
    slug: "apex-commerce-engine",
    description: "A blazing-fast e-commerce storefront with cart management, inventory tracking, order processing, and multi-currency support. Optimized for conversion with ISR caching and edge functions.",
    category: "ecommerce",
    techStack: ["Next.js 14", "Tailwind CSS", "Paystack", "M-Pesa", "Neon DB"],
    features: [
      "Multi-currency checkout (USD/KES)",
      "M-Pesa STK Push integration",
      "Paystack card payments",
      "Inventory management",
      "Order tracking system",
      "Admin product dashboard",
    ],
    priceUsd: 69,
    priceKes: 9200,
    isFree: false,
    livePreviewUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop",
    screenshots: [],
    isPublished: true,
    downloadCount: 892,
  },
  {
    id: "3",
    title: "Minimalist Creator Folio",
    slug: "minimalist-creator-folio",
    description: "A stunning portfolio template for developers, designers, and creatives. Features smooth scroll animations, project showcases, blog integration, and a contact form with Resend email delivery.",
    category: "portfolio",
    techStack: ["Next.js 14", "Tailwind CSS", "Framer Motion", "Resend"],
    features: [
      "Smooth scroll animations",
      "Project showcase with filtering",
      "Blog with MDX support",
      "Contact form with email delivery",
      "SEO-optimized metadata",
      "Social link integration",
    ],
    priceUsd: 0,
    priceKes: 0,
    isFree: true,
    livePreviewUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop",
    screenshots: [],
    isPublished: true,
    downloadCount: 3421,
  },
  {
    id: "4",
    title: "Nexus Admin Dashboard",
    slug: "nexus-admin-dashboard",
    description: "A comprehensive admin panel with data visualization, user tables, form builders, and file uploads. Features a collapsible sidebar, breadcrumb navigation, and toast notifications.",
    category: "dashboard",
    techStack: ["Next.js 14", "Tailwind CSS", "Recharts", "Uploadthing", "Clerk"],
    features: [
      "Collapsible sidebar navigation",
      "Data visualization charts",
      "Sortable/filterable data tables",
      "File upload with drag-drop",
      "Form validation with Zod",
      "Toast notification system",
    ],
    priceUsd: 59,
    priceKes: 7800,
    isFree: false,
    livePreviewUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&h=600&fit=crop",
    screenshots: [],
    isPublished: true,
    downloadCount: 1563,
  },
  {
    id: "5",
    title: "Velocity Landing Page",
    slug: "velocity-landing-page",
    description: "A high-conversion landing page template with hero sections, feature grids, pricing tables, testimonials, and FAQ accordions. Built for performance with optimized images and minimal JavaScript.",
    category: "landing",
    techStack: ["Next.js 14", "Tailwind CSS", "Framer Motion"],
    features: [
      "Hero section with CTA",
      "Feature grid with icons",
      "Pricing table comparison",
      "Testimonial carousel",
      "FAQ accordion",
      "Newsletter signup form",
    ],
    priceUsd: 0,
    priceKes: 0,
    isFree: true,
    livePreviewUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=600&fit=crop",
    screenshots: [],
    isPublished: true,
    downloadCount: 5102,
  },
  {
    id: "6",
    title: "CryptoVault Dashboard",
    slug: "cryptovault-dashboard",
    description: "A crypto portfolio tracker with real-time price feeds, portfolio allocation charts, transaction history, and wallet integration. Dark theme optimized for extended viewing sessions.",
    category: "dashboard",
    techStack: ["Next.js 14", "Tailwind CSS", "Recharts", "WebSocket", "Neon DB"],
    features: [
      "Real-time price tickers",
      "Portfolio allocation charts",
      "Transaction history table",
      "Wallet balance tracking",
      "Price alert notifications",
      "Export to CSV/JSON",
    ],
    priceUsd: 79,
    priceKes: 10500,
    isFree: false,
    livePreviewUrl: "#",
    thumbnailUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=600&fit=crop",
    screenshots: [],
    isPublished: true,
    downloadCount: 678,
  },
]
